version: '3.8'

services:
  app:
    build: .
    command: >
      sh -c "python main.py"
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
    environment:
      - psql_host=db                    # маленькие буквы
      - psql_port=5432
      - psql_user=postgres
      - psql_pass=Yjdsqgfhjkm10
      - psql_bd_name=sii
      - psql_url=postgresql://postgres:Yjdsqgfhjkm10@db/sii
      - redis_host=redis                 # маленькие буквы
      - redis_port=6379
      - redis_db_number=0
      - MAX_CONNECTIONS=10
      - MIN_CONNECTIONS=1
      - LIFE_TIME=86400
      - TIMEOUT=10
      - SWAGGER_NAME=dev
      - SWAGGER_PASS=1234
    depends_on:
      - redis
      - db
    networks:
      - app-network

  celery-worker:
    image: web-simulations:dev
    restart: always
    command: [
      "celery","-A","celery_app","worker",
      "--loglevel=info",
      "--pool=prefork",
      "--concurrency=4",
      "--prefetch-multiplier=1",
      "--queues=celery",
      "--hostname=worker@%h",
      "--without-mingle",
      "--without-gossip"
    ]
    volumes:
      - ./static:/app/static
    environment:
      - psql_host=db                    # маленькие буквы
      - psql_port=5432
      - psql_user=postgres
      - psql_pass=Yjdsqgfhjkm10
      - psql_bd_name=sii
      - psql_url=postgresql://postgres:Yjdsqgfhjkm10@db/sii
      - redis_host=redis                 # маленькие буквы
      - redis_port=6379
      - redis_db_number=0
      - MAX_CONNECTIONS=10
      - MIN_CONNECTIONS=1
      - LIFE_TIME=86400
      - TIMEOUT=10
      - SWAGGER_NAME=dev
      - SWAGGER_PASS=1234
    depends_on:
      - redis
      - db
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=sii
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Yjdsqgfhjkm10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  redis_data:
  postgres_data:

networks:
  app-network:
    driver: bridge